config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: :login, sign_out: :logout }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :tasks, only: [ :index, :create, :update, :destroy ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    redirect_to tasks_path if user_signed_in?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tasks = Task.all
    @task = Task.new
    @editing_task = Task.find(params[:edit_id]) if params[:edit_id]
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id

    if @task.save
      redirect_to @task
    else
      render :index
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
    <div class="relative isolate overflow-hidden bg-gray-900 px-6 pt-16 shadow-2xl sm:rounded-3xl sm:px-16 md:pt-24 lg:flex lg:gap-x-20 lg:px-24 lg:pt-0">
      <svg viewBox="0 0 1024 1024" aria-hidden="true" class="absolute top-1/2 left-1/2 -z-10 size-256 -translate-y-1/2 mask-[radial-gradient(closest-side,white,transparent)] sm:left-full sm:-ml-80 lg:left-1/2 lg:ml-0 lg:-translate-x-1/2 lg:translate-y-0">
        <circle r="512" cx="512" cy="512" fill="url(#759c1415-0410-454c-8f7c-9a820de03641)" fill-opacity="0.7" />
        <defs>
          <radialGradient id="759c1415-0410-454c-8f7c-9a820de03641">
            <stop stop-color="#7775D6" />
            <stop offset="1" stop-color="#E935C1" />
          </radialGradient>
        </defs>
      </svg>
      <div class="mx-auto max-w-md text-center lg:mx-0 lg:flex-auto lg:py-32 lg:text-left">
        <h2 class="text-3xl font-semibold tracking-tight text-balance text-white sm:text-4xl"> Hi, everyone! Start using today. </h2>
        <p class="mt-6 text-lg/8 text-pretty text-gray-300"> Make your list of tasks, purchases. </p>
        <div class="mt-10 flex items-center justify-center gap-x-6 lg:justify-start">
          <a href="/users/login" class="rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-xs hover:bg-gray-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white"> Get Started </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title><%= content_for(:title) || "To Do App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/_new_form.html.erb
<%= render 'devise/shared/error_messages', resource: @task %>

<%= form_with model: task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "New task" %>
    <p>
      <%= f.submit %>
    <p/>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% if @tasks.present? %>
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <% if @editing_task == task %>
          <%= form_with model: task do |f| %>
            <%= f.text_field :title %>
            <%= f.check_box :completed %>
            <%= f.submit "Update" %>
            <%= link_to "Cancel", tasks_path %>
          <% end %>
        <% else %>
          <%= task.title %>
          <%= task.completed %> 
          <%= link_to "Edit", tasks_path(edit_id: task.id) %>
          <%= link_to "Delete", task_path(task), 
                          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
  

app/views/tasks/index.html.erb
<h2>Add new task</h2>
<%= render "tasks/new_form", task: @task %>
<p>
  <h1>Your Tasks</h1>
    <%= render @task %>
</p>

<p><%= link_to "Exit", destroy_user_session_path %></p>